# menu
author: eneim # 作者
description: "eneim's blog"
keyword: hexo-theme, vuejs

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Github: https://github.com/eneim
 # Projects: /project/
 About: /about/

# highlight
highlight:
  #default
  #github
  #atom-one-light
  github-gist
  #tomorrow

# gitment
gitment_owner: eneim
gitment_repo: eneim.github.io
gitment_oauth_id: b0a642955d0041f4e008
gitment_oauth_secret: c20bc1d4b284e3219213dd8c4bd8cb0ab70c566f

# Disqus
disqus_shortname: eneim

about: 
  banner: http://68.media.tumblr.com/1d81646b36cefa01093981368ad2ed93/tumblr_ncgnff0UOb1rsj2h0o7_1280.jpg
  avatar: https://www.gravatar.com/avatar/f8ca3e94570e4dc117f34563687a3b09?s=360
  description: the simple, the best
