# menu
author: eneim # 作者
description: "eneim's blog"
keyword: the simple, the best # seo keyword

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Github: https://github.com/eneim

# highlight
highlight:
  tomorrow

# gitment
gitment_owner: eneim
gitment_repo: eneim.github.io
gitment_oauth_id: b0a642955d0041f4e008
gitment_oauth_secret: c20bc1d4b284e3219213dd8c4bd8cb0ab70c566f

# Disqus
disqus_shortname: eneim